version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./jobsearchcatalog/.env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
       - ./jobsearchcatalog/:/jobserachcatalog/

    environment:
      - POSTGRES_USER=luba93
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job
volumes:
  postgres_data:





