# Generated by Django 3.1.7 on 2021-03-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=512)),
                ('tax_number', models.CharField(max_length=64)),
                ('legal_address', models.CharField(max_length=255)),
                ('work_sector', models.CharField(max_length=512)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
